services:
  db_dev:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cv_app
    ports:
      - "3307:3306"

  db_test:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cv_test
    ports:
      - "3308:3306"
